apiVersion: v1
kind: Service
metadata:
  name: todo-application-service
spec:
  selector:
    app: todo-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort