apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: log-output-writer
        image: valeriot015/log-output-writer:latest
        volumeMounts:
        - name: shared-data
          mountPath: /data
      - name: log-output-reader
        image: valeriot015/log-output-reader:latest
        volumeMounts:
        - name: shared-data
          mountPath: /data