apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-cache-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kube-image-cache"